### ISSUE TITLE
Cannot find module 'asn1' error after update to 2.5.0

### ISSUE THREAD

**Issue by Rutul27** [MichMich/MagicMirror#1422]
**Platform**:  Raspberry Pi 3

**NPM**:  6.4.1

**Electron**:  2.0.11

**Node Version**: 10.10.0

**MagicMirror Version**:  2.5.0

**Description**: After updating to the new version from 2.4.1, I started getting this error and it's giving black screen after npm start. I figured that it must be an error with node or electron and tried to update both to the latest versions, but still, the error is there.

Error message:

WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'asn1'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
App threw an error during load
Error: Cannot find module 'asn1'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/sshpk/lib/formats/pem.js:9:12)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/sshpk/lib/formats/pem.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module 'asn1'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/sshpk/lib/formats/pem.js:9:12)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/sshpk/lib/formats/pem.js:188:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }

![error](https://user-images.githubusercontent.com/23465024/46335117-55a22700-c5db-11e8-9d29-8a5d8ae3142c.PNG)

**Comment by Rutul27** [comment]
Fix: 
cd MagicMirror
npm install asn1
