### ISSUE TITLE
Error: Cannot find module 'envsub' / failed to load swrast driver

### ISSUE THREAD

**Issue by JVoelkers** [MichMich/MagicMirror#3102]
Having continual issues with MagicMirror since updating to 2.23.0 seem to be getting two errors in the same run Error: Cannot find module 'envsub' AND failed to load swrast driver

`pi@raspberrypi:~/MagicMirror $ npm run start

> magicmirror@2.23.0 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

App threw an error during load
Error: Cannot find module 'envsub'
Require stack:
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/MagicMirror/js/app.js:13:16)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'envsub'
Require stack:
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/MagicMirror/js/app.js:13:16)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open kms_swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load swrast driver

`

**Comment by sdetweil** [comment]
that means you did not run install , or it did not complete

the update process is 
```
git clone
npm run install-mm
```

the npm run does the npm install with a set of parms that reduce the noise

**Comment by valemichelleee** [comment]
I also have the same problem with MMM-mvgmunich module. I did reclone the git repo and run npm install, but nothing changed. Any help?

**Comment by khassel** [comment]
> that means you did not run npm install , or it did not complete

correct, if someone still have this problem, the update process is documented [here](https://docs.magicmirror.builders/getting-started/upgrade-guide.html).

**Comment by sdetweil** [comment]
we still have quite a few that don't understand the full process..
